"""Gate contract probes (decision 0009) for literal text glued onto a
rendered placeholder, malformed placeholders, and fact amounts that
repeat the floor under --approved.

Generated by the /ship test coverage audit.
"""

import unittest

from bt_helpers import (
    approve_held,
    BRIEF_PAY,
    BtTestCase,
    new_case,
    plan_for,
    run_bt_json,
    send_draft,
    write_case_files,
    write_draft,
)

LIMITS = "outside your limits; escalate to the user"


class GluedTest(BtTestCase):
    def make_case(self, floor=1200, plan=None):
        case_id, case_dir = new_case(self.home, direction="pay")
        write_case_files(
            case_dir,
            brief=dict(BRIEF_PAY, direction="pay"),
            plan=plan_for("pay", floor) if plan is None else plan,
            floor=floor,
        )
        return case_id

    def gate(self, case_id, draft, approved=False):
        path = write_draft(self.tmp, draft)
        args = ["gate", case_id, "--draft", str(path)]
        if approved:
            args = approve_held(self.home, case_id, args)
        return run_bt_json(self.home, *args)


class ScaleSuffixGluedTest(GluedTest):
    # Value: protects=0009 C review tier: a scale suffix glued to a
    #   rendered amount ("$1,100k") routes to the user, never a silent
    #   pass; fails_when=the masked scan cannot see the digit before "k"
    #   or "m" (current HEAD) or the scale-word check is dropped;
    # why_new=test_currency_and_scale_words covers free-text "5k" and
    #   "thousand" only, never a suffix after a masked placeholder;
    #   seam=none
    def test_scale_suffix_after_placeholder_is_not_a_silent_pass(self):
        # Offer 1100 is inside a pay floor of 1200, but "$1,100k" states
        # 1,100,000 to the counterparty. The literal text changes the
        # amount, so the user must see it.
        case_id = self.make_case()
        for template in (
            "I can do {offer}k today",
            "I can do {offer}K today",
            "I can do {offer}m today",
            "our budget is {target}k",
        ):
            with self.subTest(template=template):
                proc, out = self.gate(case_id, send_draft(template=template))
                self.assertNotEqual(out["result"], "pass", out)
                self.assertEqual(out["result"], "needs_approval", out)
                self.assertEqual(proc.returncode, 3, out)


class DecimalTailGluedTest(GluedTest):
    # Value: protects=0009 C "a digit next to a rendered amount": a
    #   decimal tail glued to {offer} that restates a price past the
    #   floor routes to the user; fails_when=only a bare digit right
    #   after the mask counts (current HEAD) so "{offer}.99" passes;
    # why_new=test_digit_adjacent_to_offer_output covers "{offer}0"
    #   only, not a separator plus digits; seam=none
    def test_decimal_tail_after_offer_is_not_a_silent_pass(self):
        # Floor 1100.50 pay, offer 1100 is in band. "{offer}.99" sends
        # "$1,100.99", which is worse than the floor.
        case_id = self.make_case(
            floor=1100.50, plan=plan_for("pay", 1100.50, target=1000)
        )
        for template in ("I can do {offer}.99 today", "I can do {offer},99 today"):
            with self.subTest(template=template):
                proc, out = self.gate(
                    case_id, send_draft(offer=1100, template=template)
                )
                self.assertNotEqual(out["result"], "pass", out)
                self.assertEqual(proc.returncode, 3, out)


class MalformedPlaceholderTest(GluedTest):
    # Value: protects=0009 A "unknown or malformed placeholders" hard
    #   block: an unclosed or doubled brace never ships verbatim;
    # fails_when=TAG only matches balanced {..} so "{offer" passes as
    #   literal text (current HEAD); why_new=test_placeholder_error_table
    #   covers unknown names and bad indexes, not brace shape; seam=none
    def test_unbalanced_braces_block(self):
        case_id = self.make_case()
        for template in ("price is {offer", "price is {{offer}}"):
            with self.subTest(template=template):
                proc, out = self.gate(case_id, send_draft(template=template))
                self.assertEqual(out["result"], "block", out)
                self.assertEqual(proc.returncode, 1, out)
                self.assertIsNone(out["rendered"])

    # Value: protects=0009 A "unknown or malformed placeholders" hard
    #   block: a lone "}" or a nested pair inside outer braces is as
    #   malformed as an unclosed "{" and must never ship verbatim;
    # fails_when=only "{" is treated as a tag opener, so "offer}" or
    #   "{ {offer} }" passes as literal text with an inner tag;
    # why_new=test_unbalanced_braces_block covers "{offer" and
    #   "{{offer}}", never a stray closer alone; seam=none
    def test_lone_closing_brace_blocks(self):
        case_id = self.make_case()
        for template in ("price is offer}", "{ {offer} }"):
            with self.subTest(template=template):
                proc, out = self.gate(case_id, send_draft(template=template))
                self.assertEqual(out["result"], "block", out)
                self.assertEqual(proc.returncode, 1, out)
                self.assertIsNone(out["rendered"])
                self.assertIn(
                    "malformed placeholder", " ".join(out["reasons"])
                )


class FactAmountAtFloorTest(GluedTest):
    # Value: protects=0010 A: a rendered fact whose structured amount
    #   equals the floor hard-blocks even with --approved; an amount
    #   equal only after a period conversion is a review hit, not a
    #   block; fails_when=render stops recording fact amounts or
    #   _check_values skips kind "fact", so --approved (no review)
    #   ships the floor; why_new=fact tests only assert needs_approval
    #   without --approved; seam=none
    def test_fact_repeating_floor_blocks_even_when_approved(self):
        plan = dict(
            plan_for("pay", 1200),
            facts=[
                {"id": "eq", "text": "they first quoted $1,200",
                 "source": "x", "amount": 1200},
                {"id": "mo", "text": "that is $100 a month",
                 "source": "x", "amount": 100, "period": "month"},
                {"id": "ok", "text": "competitor charges $89 a month",
                 "source": "x", "amount": 89, "period": "month"},
            ],
        )
        case_id = self.make_case(plan=plan)
        proc, out = self.gate(
            case_id,
            send_draft(template="note: {fact:eq}"),
            approved=True,
        )
        self.assertEqual(proc.returncode, 1, out)
        self.assertEqual(out["reasons"], [LIMITS])
        self.assertIsNone(out["rendered"])
        # $100 is the floor /12: a converted match, a review hit only.
        proc, out = self.gate(
            case_id, send_draft(template="note: {fact:mo}")
        )
        self.assertEqual(proc.returncode, 3, out)
        self.assertIn("converted limit", " ".join(out["reasons"]))
        proc, out = self.gate(
            case_id, send_draft(template="note: {fact:mo}"),
            approved=True,
        )
        self.assertEqual(proc.returncode, 0, out)
        # Control: a fact amount unrelated to the floor ships approved.
        proc, out = self.gate(
            case_id, send_draft(template="note: {fact:ok}"), approved=True
        )
        self.assertEqual(proc.returncode, 0, out)
        self.assertIn("$89 a month", out["rendered"])


class OptionPeriodTest(GluedTest):
    # Value: protects=0009 B: bonus and fee options skip the floor
    #   check but their period is still plan data that must parse; an
    #   invalid period is a broken case file, so exit 2 with a plain
    #   error; fails_when=check_plan_limits validates price options
    #   only, so a bonus period reaches convert() and dies as
    #   "unexpected KeyError"; why_new=test_bonus_fee_options_floor_rules
    #   covers valid kinds and values only; seam=none
    def test_bonus_fee_option_bad_period_exits_2_plainly(self):
        for kind in ("bonus", "fee"):
            with self.subTest(kind=kind):
                plan = dict(
                    plan_for("pay", 1200),
                    period="month",
                    options=[
                        {"label": "x", "value": 100, "kind": kind,
                         "period": "week"},
                    ],
                )
                case_id = self.make_case(plan=plan)
                proc, out = self.gate(
                    case_id, send_draft(template="note {option:x}")
                )
                self.assertEqual(proc.returncode, 2, out)
                self.assertIn(
                    "plan.yaml options[0].period: must be once,"
                    " month or year",
                    out["error"],
                )
                self.assertNotIn("KeyError", out["error"])


if __name__ == "__main__":
    unittest.main()
