import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts._lib import miniyaml

# Shape mirrors `plan.yaml` in docs/plans/2026-10-03-betterterms-v1.md
# ("Shared interfaces"): scalar fields, a nested map, and lists of maps.
SAMPLE_PLAN = """\
# written by betterterms-plan
target: 70
currency: USD
options:
  - label: annual
    value: 65
    terms: 12-month prepay
  - label: monthly
    value: 80
    terms: cancel anytime
ladder:
  - value: 70
    reason: target
  - value: 85
    reason: fallback if pushed
patience:
  rounds: 3
  days: 14
timing: before renewal
channel: email
facts:
  - id: f1
    text: competitor charges $89 per month
    source: https://example.com/pricing
  - id: f2
    text: "policy allows retention offers"
    source: https://example.com/policy
"""


class LoadTest(unittest.TestCase):
    def test_inline_list(self):
        self.assertEqual(miniyaml.load("a: [1, 2]"), {"a": [1, 2]})

    def test_sample_plan_shape(self):
        plan = miniyaml.load(SAMPLE_PLAN)
        self.assertEqual(plan["target"], 70)
        self.assertEqual(
            plan["options"][0],
            {"label": "annual", "value": 65, "terms": "12-month prepay"},
        )
        self.assertEqual(plan["patience"], {"rounds": 3, "days": 14})
        self.assertEqual(plan["facts"][1]["id"], "f2")

    def test_tab_indentation_raises_with_line_number(self):
        with self.assertRaises(miniyaml.Error) as cm:
            miniyaml.load("\ta: 1")
        self.assertIn("line 1", str(cm.exception))

    def test_dollar_amount_stays_string(self):
        out = miniyaml.load('price: "$1,200"')
        self.assertEqual(out, {"price": "$1,200"})
        self.assertIsInstance(out["price"], str)

    def test_scalar_types(self):
        out = miniyaml.load("i: 3\nf: 1.5\nb: true\nn: null\ns: hello\n")
        self.assertEqual(out, {"i": 3, "f": 1.5, "b": True, "n": None, "s": "hello"})

    def test_block_scalar(self):
        out = miniyaml.load("text: |\n  first line\n  second line\nnext: 1\n")
        self.assertEqual(out["text"], "first line\nsecond line\n")
        self.assertEqual(out["next"], 1)

    def test_missing_colon_raises(self):
        with self.assertRaises(miniyaml.Error):
            miniyaml.load("a: 1\njust text\n")

    # Generated by /ship coverage audit.
    # Value: protects=a duplicate mapping key raises naming its line instead of
    # silently overwriting plan data; fails_when=the duplicate-key guard in
    # _Parser.map is removed; why_new=no test loads a repeated key; seam=none
    def test_duplicate_key_raises_with_line_number(self):
        with self.assertRaises(miniyaml.Error) as cm:
            miniyaml.load("target: 70\ncurrency: USD\ntarget: 85\n")
        self.assertIn("line 3", str(cm.exception))
        self.assertIn("duplicate key", str(cm.exception))

    # Generated by /ship coverage audit.
    # Value: protects=folded '>' joins lines and keeps paragraph breaks; '-'
    # strips and '+' keeps trailing newlines; fails_when=folding or chomping in
    # block_scalar regresses; why_new=only literal '|' is tested; seam=none
    def test_folded_and_chomped_block_scalars(self):
        out = miniyaml.load(
            "desc: >\n  one\n  two\n\n  three\n"
            "strip: |-\n  kept\n"
            "keep: |+\n  kept\n\n"
            "after: 1\n"
        )
        self.assertEqual(out["desc"], "one two\nthree\n")
        self.assertEqual(out["strip"], "kept")
        self.assertEqual(out["keep"], "kept\n\n")
        self.assertEqual(out["after"], 1)

    # Generated by /ship coverage audit.
    # Value: protects=same-indent sequences under a key, '#' comments vs '#'
    # inside quotes or words, a leading '---', and empty docs loading as None;
    # fails_when=value_after_key, _strip_comment or the '---' skip in parse()
    # regresses; why_new=no test loads these documented subset rules; seam=none
    def test_same_indent_seq_comments_and_doc_marker(self):
        self.assertEqual(
            miniyaml.load("items:\n- a\n- b\nnext: 1\n"),
            {"items": ["a", "b"], "next": 1},
        )
        self.assertEqual(
            miniyaml.load('note: "a # b"  # trailing\nurl: x#y\n'),
            {"note": "a # b", "url": "x#y"},
        )
        self.assertEqual(miniyaml.load("---\na: 1\n"), {"a": 1})
        self.assertIsNone(miniyaml.load(""))
        self.assertIsNone(miniyaml.load("# only a comment\n---\n"))

    def test_bad_hex_escape_raises_error(self):
        for src in ('k: "\\xzz"', 'k: "\\u12"', 'k: "\\x4"', 'k: "\\x"'):
            with self.subTest(src=src):
                with self.assertRaises(miniyaml.Error):
                    miniyaml.load(src)

    def test_flow_trailing_comma_does_not_append_none(self):
        self.assertEqual(miniyaml.load("a: [x, y,]"), {"a": ["x", "y"]})
        self.assertEqual(miniyaml.load("a: {k: 1,}"), {"a": {"k": 1}})

    def test_indicator_prefixed_scalars_raise(self):
        for src in ("k: *alias", "k: &anc", "k: !tag", "k: %d", "k: @x", "k: `x"):
            with self.subTest(src=src):
                with self.assertRaises(miniyaml.Error):
                    miniyaml.load(src)

    def test_split_on_newline_only_strips_trailing_cr(self):
        self.assertEqual(miniyaml.load("a: 1\r\nb: 2\r\n"), {"a": 1, "b": 2})
        self.assertEqual(miniyaml.load("a: x\ry\n"), {"a": "x\ry"})

    def test_folded_keeps_more_indented_line_breaks(self):
        out = miniyaml.load(
            "d: >\n  one\n  two\n    code\n    more code\n  three\nnext: 1\n"
        )
        self.assertEqual(out["d"], "one two\n  code\n  more code\nthree\n")
        self.assertEqual(out["next"], 1)


class DumpTest(unittest.TestCase):
    def test_round_trip_sample_plan(self):
        plan = miniyaml.load(SAMPLE_PLAN)
        self.assertEqual(miniyaml.load(miniyaml.dump(plan)), plan)

    def test_round_trip_scalars_and_nested(self):
        obj = {
            "a": [1, "two", None, True, 2.5],
            "b": {"c": "x: y", "d": "$1,200", "e": "trailing "},
            "empty_list": [],
            "empty_map": {},
            "multiline": "one\ntwo",
        }
        self.assertEqual(miniyaml.load(miniyaml.dump(obj)), obj)

    # Generated by /ship coverage audit.
    # Value: protects=dump refuses values and keys it cannot round-trip instead
    # of writing lossy YAML; fails_when=_scalar_repr or _key_repr falls back to
    # str(); why_new=dump tests cover only supported types; seam=none
    def test_unsupported_value_or_key_raises(self):
        with self.assertRaises(miniyaml.Error):
            miniyaml.dump({"s": {1, 2}})
        with self.assertRaises(miniyaml.Error):
            miniyaml.dump({(1, 2): "x"})

    def test_nonfinite_float_dump_raises(self):
        for v in (float("inf"), float("-inf"), float("nan")):
            with self.subTest(v=v):
                with self.assertRaises(miniyaml.Error):
                    miniyaml.dump({"v": v})

    def test_ambiguous_strings_dump_quoted_and_round_trip(self):
        for s in ("yes", "NO", "On", "y", "n", "off", "~", "2026-10-03",
                  "0x1F", "0o17", "007", "1e5", "a;b", "a [b", "it's",
                  'say "hi"'):
            with self.subTest(s=s):
                out = miniyaml.dump({"k": s})
                self.assertIn('"', out)
                self.assertEqual(miniyaml.load(out), {"k": s})

    def test_dump_escapes_use_json_style(self):
        self.assertEqual(miniyaml.dump({"k": "a\x07b"}), 'k: "a\\u0007b"\n')
        obj = {"k": "a\x07b\ncafé \"q\" \\ end"}
        self.assertEqual(miniyaml.load(miniyaml.dump(obj)), obj)


if __name__ == "__main__":
    unittest.main()
