import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts._lib import miniyaml

# Shape mirrors `plan.yaml` in docs/plans/2026-10-03-betterterms-v1.md
# ("Shared interfaces"): scalar fields, a nested map, and lists of maps.
SAMPLE_PLAN = """\
# written by betterterms-plan
target: 70
currency: USD
options:
  - label: annual
    value: 65
    terms: 12-month prepay
  - label: monthly
    value: 80
    terms: cancel anytime
ladder:
  - value: 70
    reason: target
  - value: 85
    reason: fallback if pushed
patience:
  rounds: 3
  days: 14
timing: before renewal
channel: email
facts:
  - id: f1
    text: competitor charges $89 per month
    source: https://example.com/pricing
  - id: f2
    text: "policy allows retention offers"
    source: https://example.com/policy
"""


class LoadTest(unittest.TestCase):
    def test_sample_plan_shape(self):
        plan = miniyaml.load(SAMPLE_PLAN)
        self.assertEqual(plan["target"], 70)
        self.assertEqual(
            plan["options"][0],
            {"label": "annual", "value": 65, "terms": "12-month prepay"},
        )
        self.assertEqual(plan["patience"], {"rounds": 3, "days": 14})
        self.assertEqual(plan["facts"][1]["id"], "f2")

    def test_scalar_types(self):
        out = miniyaml.load("i: 3\nf: 1.5\nb: true\nn: null\ns: hello\n")
        self.assertEqual(out, {"i": 3, "f": 1.5, "b": True, "n": None, "s": "hello"})
        # Extended by /ship coverage audit (plan's named assertion).
        # Value: protects=flow sequences load as lists of ints; fails_when=flow
        # collections or int resolution break in the loader; why_new=flow lists
        # are only checked via frontmatter strings; seam=none
        self.assertEqual(miniyaml.load("a: [1, 2]"), {"a": [1, 2]})

    def test_dollar_amount_stays_string(self):
        out = miniyaml.load('price: "$1,200"')
        self.assertEqual(out, {"price": "$1,200"})
        self.assertIsInstance(out["price"], str)

    def test_yaml_error_becomes_error_with_line(self):
        with self.assertRaises(miniyaml.Error) as cm:
            miniyaml.load("\ta: 1\n")
        self.assertEqual(cm.exception.line, 1)
        self.assertIn("line 1", str(cm.exception))
        with self.assertRaises(miniyaml.Error) as cm:
            miniyaml.load("name: x\ndescription: a: b\n")
        self.assertEqual(cm.exception.line, 2)

    def test_error_without_mark_has_no_line(self):
        with self.assertRaises(miniyaml.Error) as cm:
            miniyaml.load(42)
        self.assertIsNone(cm.exception.line)

    # Value: protects=a duplicate mapping key raises naming its line instead of
    # silently overwriting plan data; fails_when=the duplicate-key guard in
    # _Loader.construct_mapping is removed; seam=none
    def test_duplicate_key_raises_with_line_number(self):
        with self.assertRaises(miniyaml.Error) as cm:
            miniyaml.load("target: 70\ncurrency: USD\ntarget: 85\n")
        self.assertEqual(cm.exception.line, 3)
        self.assertIn("duplicate key", str(cm.exception))

    def test_merge_key_inline_map_merges(self):
        out = miniyaml.load("merged:\n  <<: {x: 1, y: 2}\n  z: 3\n")
        self.assertEqual(out["merged"], {"x": 1, "y": 2, "z": 3})

    def test_merge_key_sequence_merges_in_order(self):
        # First map in the sequence wins on shared keys, like safe_load.
        out = miniyaml.load("m:\n  <<: [{a: 1, b: 1}, {b: 2, c: 2}]\n")
        self.assertEqual(out["m"], {"a": 1, "b": 1, "c": 2})

    def test_explicit_key_overrides_merged_key_like_safe_load(self):
        self.assertEqual(
            miniyaml.load("m:\n  <<: {a: 1}\n  a: 9\n"), {"m": {"a": 9}}
        )

    def test_alias_raises_error_but_anchor_alone_is_fine(self):
        with self.assertRaises(miniyaml.Error) as cm:
            miniyaml.load("a: &x 1\nb: *x\n")
        self.assertIn("alias", str(cm.exception))
        self.assertIsNotNone(cm.exception.line)
        self.assertEqual(miniyaml.load("a: &x 1\n"), {"a": 1})

    def test_alias_bomb_and_merge_alias_raise_error(self):
        bomb = "a: &a [x,x,x,x,x,x,x,x]\nb: [*a, *a, *a]\n"
        with self.assertRaises(miniyaml.Error):
            miniyaml.load(bomb)
        with self.assertRaises(miniyaml.Error):
            miniyaml.load("d: &d {x: 1}\nm:\n  <<: *d\n")

    def test_docstring_is_location_neutral(self):
        # This file is byte-copied into the guardrails skill's btlib, so
        # the docstring cannot name repo-rooted paths.
        self.assertNotIn("scripts/", miniyaml.__doc__)
        self.assertNotIn("btlib", miniyaml.__doc__)
        self.assertIn("_vendor", miniyaml.__doc__)

    # Generated by /ship coverage audit.
    # Value: protects=an unhashable (list or map) mapping key raises
    # miniyaml.Error with a line, never a bare TypeError or YAMLError;
    # fails_when=the TypeError guard in _Loader.construct_mapping is removed or
    # re-raises; why_new=only hashable duplicate keys are tested; seam=none
    def test_unhashable_key_raises_error_not_type_error(self):
        for text in ("? [a]\n: 1\n", "ok: 1\n? {a: 1}\n: 2\n"):
            with self.subTest(text=text):
                with self.assertRaises(miniyaml.Error) as cm:
                    miniyaml.load(text)
                self.assertIn("unhashable key", str(cm.exception))
                self.assertIsNotNone(cm.exception.line)


class DumpTest(unittest.TestCase):
    def test_round_trip_sample_plan(self):
        plan = miniyaml.load(SAMPLE_PLAN)
        self.assertEqual(miniyaml.load(miniyaml.dump(plan)), plan)

    def test_round_trip_nested_types(self):
        obj = {
            "str": "text",
            "int": 3,
            "float": 2.5,
            "bool": True,
            "none": None,
            "list": [1, "two", None, False],
            "dict": {"nested": {"deep": "x: y"}},
            "empty_list": [],
            "empty_map": {},
            "unicode": "café",
        }
        self.assertEqual(miniyaml.load(miniyaml.dump(obj)), obj)

    def test_dump_is_block_style_sorted_off(self):
        out = miniyaml.dump({"b": 1, "a": [1, 2]})
        self.assertEqual(out, "b: 1\na:\n- 1\n- 2\n")

    def test_unsupported_value_raises_error(self):
        with self.assertRaises(miniyaml.Error):
            miniyaml.dump({"k": object()})


if __name__ == "__main__":
    unittest.main()
