import time
import unittest
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "skills" / "betterterms-guardrails" / "scripts"))

from btlib import money


class AmountsTest(unittest.TestCase):
    def test_dollar_commas(self):
        self.assertEqual(money.amounts("$1,200"), [1200.0])

    def test_decimal(self):
        self.assertEqual(money.amounts("1200.00"), [1200.0])

    def test_k_suffix(self):
        self.assertEqual(money.amounts("1.2k"), [1200.0])

    def test_currency_code(self):
        self.assertEqual(money.amounts("USD 1200"), [1200.0])

    def test_currency_symbol_code(self):
        self.assertEqual(money.amounts("S$1,200"), [1200.0])

    def test_spelled_hundreds(self):
        self.assertEqual(money.amounts("twelve hundred"), [1200.0])

    def test_spelled_thousands(self):
        self.assertIn(1200.0, money.amounts("one thousand two hundred"))

    def test_spelled_millions(self):
        self.assertIn(2000000.0, money.amounts("two million"))

    def test_spelled_with_currency_word(self):
        self.assertIn(350000.0, money.amounts("three hundred fifty thousand dollars"))

    def test_dollars_suffix(self):
        self.assertEqual(money.amounts("1200 dollars"), [1200.0])

    def test_fact_id_is_not_an_amount(self):
        self.assertEqual(money.amounts("claim f9 is wrong"), [])

    def test_no_amounts(self):
        self.assertEqual(money.amounts("see you next week"), [])

    def test_currency_and_bare_amounts(self):
        self.assertEqual(
            money.amounts("pay $1,200 over 3 years"), [1200.0, 3.0]
        )
        self.assertIn(3.0, money.amounts("I have 3 options"))

    # Generated by /ship coverage audit.
    # Value: protects=compact scale suffixes parse to full amounts: 5m and
    # 5mm are 5,000,000, 2bn is 2,000,000,000; fails_when=a suffix is
    # dropped from the multiplier table or "mm" is left unread;
    # why_new=only the k suffix was tested; seam=none
    def test_compact_scale_suffixes(self):
        self.assertEqual(money.amounts("5m"), [5000000.0])
        self.assertEqual(money.amounts("5mm"), [5000000.0])
        self.assertEqual(money.amounts("2bn"), [2000000000.0])

    # Generated by /ship coverage audit.
    # Value: protects=a bare number followed by an ISO currency code is a
    # marked amount; fails_when=the code-suffix alternative in _SUFFIXED
    # is dropped; why_new=only currency prefixes and word suffixes were
    # tested; seam=none
    def test_currency_code_suffix_is_one_amount(self):
        found = money.find("send 1200 EUR today")
        self.assertEqual([a.value for a in found], [1200.0])

    # Generated by /ship coverage audit.
    # Value: protects="$1.2 million" reads as one marked 1,200,000 amount,
    # never a spurious 1.2 plus a separate million; fails_when=_MARKED
    # stops at the number and _DIGIT_SCALE emits a second overlapping
    # amount; why_new=no test put a scale word after a currency-marked
    # number; seam=none
    def test_dollar_millions_is_one_amount(self):
        found = money.find("we close at $1.2 million")
        self.assertEqual([a.value for a in found], [1200000.0])

    # Generated by /ship coverage audit.
    # Value: protects=digits plus a scale word collapse to one amount:
    # "1.5 thousand" is 1500 and "12 hundred" is 1200; fails_when=
    # _DIGIT_SCALE loses "hundred" or reports digit and scale separately;
    # why_new=scale words were only exercised spelled out; seam=none
    def test_digit_scale_words(self):
        self.assertEqual(money.amounts("1.5 thousand"), [1500.0])
        self.assertEqual(money.amounts("12 hundred"), [1200.0])

    # Every form below is one parsed amount: the gate's fact-value and
    # never-disclose checks both key off the numeric value, so leak
    # forms must arrive as amounts, not noise.

    def test_spelled_amount_with_comma(self):
        self.assertEqual(money.amounts("one thousand, two hundred"), [1200.0])
        self.assertIn(1200.0, money.amounts("one thousand, two hundred dollars"))
        self.assertIn(1200.0, money.amounts("one thousand and two hundred"))

    def test_space_grouped_thousands(self):
        self.assertIn(1200.0, money.amounts("about 1 200 today"))
        self.assertIn(1234567.0, money.amounts("1 234 567"))

    def test_grand_suffix(self):
        self.assertEqual(money.amounts("1.2 grand"), [1200.0])
        self.assertEqual(money.amounts("2 grand"), [2000.0])
        # "grand" alone is not money: spelled words never pick it up.
        self.assertEqual(money.amounts("a grand gesture"), [])

    def test_approximately(self):
        for text in ("~1200", "~ 1200", "≈1200"):
            with self.subTest(text=text):
                self.assertIn(1200.0, money.amounts(text))

    def test_ish_suffix(self):
        for text in ("1200ish", "1,200-ish", "1200 ish"):
            with self.subTest(text=text):
                self.assertIn(1200.0, money.amounts(text))

    def test_per_period(self):
        rows = [
            ("1200/mo", 1200.0),
            ("1200/month", 1200.0),
            ("1200 / month", 1200.0),
            ("1200 a month", 1200.0),
            ("1200 per month", 1200.0),
            ("1200 every month", 1200.0),
            ("50/yr", 50.0),
            ("3 a day", 3.0),
        ]
        for text, want in rows:
            with self.subTest(text=text):
                self.assertIn(want, money.amounts(text))

    def test_digit_scale_is_one_amount(self):
        self.assertEqual(money.amounts("12 hundred"), [1200.0])

    def test_spelled_scale_and_lone_unit(self):
        self.assertEqual(money.amounts("twelve hundred"), [1200.0])
        # A lone unit word is just a count: "two" parses to 2.
        self.assertIn(2.0, money.amounts("two options"))

    def test_input_capped_at_64kb(self):
        # Amounts past the cap are never read.
        text = "word " * 40000 + "$1200"  # ~200 KB
        self.assertEqual(money.amounts(text), [])
        text = "$1200 " + "word " * 40000
        self.assertEqual(money.amounts(text), [1200.0])

    def test_find_linear_time_on_hostile_input(self):
        for text in (
            "1," * 65536,           # 128 KB of "1,1,1,..."
            "1,000," * 16384,       # grouped digits, ~112 KB
            "one thousand " * 9000, # spelled run, ~117 KB
            "$ " + " " * 60000 + "one hundred " * 2000,
            "one hundred " * 2000 + " " * 60000 + "dollars",
        ):
            with self.subTest(size=len(text)):
                start = time.monotonic()
                money.find(text)
                self.assertLess(time.monotonic() - start, 1.0)

    def test_overflow_never_raises_or_yields_infinity(self):
        # "hundred" repeated compounds to 100**n; a 309-digit run
        # saturates float parsing. Neither may raise or return inf.
        import math
        for text in (
            "hundred " * 200,
            "hundred " * 200 + "dollars",
            "9" * 309,
            "$" + "9" * 309 + " billion",
            "nine " + "hundred " * 400 + "thousand",
        ):
            with self.subTest(text=text[:30]):
                values = money.amounts(text)
                self.assertTrue(values, text[:30])
                self.assertTrue(all(math.isfinite(v) for v in values))


if __name__ == "__main__":
    unittest.main()
