import unittest

from bt_helpers import BtTestCase, new_case, run_bt_json
from btlib import yaml


class LedgerTest(BtTestCase):
    def test_ledger_add_monthly(self):
        case_id, _ = new_case(self.home, pack="bills")
        proc, out = run_bt_json(
            self.home,
            "ledger", "add", case_id,
            "--before", "80", "--after", "60", "--period", "month",
        )
        self.assertEqual(proc.returncode, 0, proc.stdout)
        self.assertEqual(out["saved_per_year"], 240)

    def test_ledger_add_yearly(self):
        case_id, _ = new_case(self.home, pack="bills")
        proc, out = run_bt_json(
            self.home,
            "ledger", "add", case_id,
            "--before", "1200", "--after", "960", "--period", "year",
        )
        self.assertEqual(proc.returncode, 0, proc.stdout)
        self.assertEqual(out["saved_per_year"], 240)

    def test_ledger_add_receive_direction(self):
        case_id, _ = new_case(self.home, pack="job-offer", direction="receive")
        proc, out = run_bt_json(
            self.home,
            "ledger", "add", case_id,
            "--before", "150000", "--after", "165000", "--period", "year",
        )
        self.assertEqual(proc.returncode, 0, proc.stdout)
        self.assertEqual(out["saved_per_year"], 15000)

    def test_ledger_total_sums_by_pack(self):
        c1, _ = new_case(self.home, pack="bills")
        c2, _ = new_case(self.home, pack="subscriptions")
        run_bt_json(self.home, "ledger", "add", c1,
                    "--before", "80", "--after", "60", "--period", "month")
        run_bt_json(self.home, "ledger", "add", c2,
                    "--before", "50", "--after", "40", "--period", "month")
        proc, out = run_bt_json(self.home, "ledger", "total")
        self.assertEqual(proc.returncode, 0, proc.stdout)
        self.assertEqual(out["cases"], 2)
        self.assertEqual(out["saved_per_year"], 360)
        self.assertEqual(out["by_pack"], {"bills": 240, "subscriptions": 120})

    def test_ledger_total_empty(self):
        proc, out = run_bt_json(self.home, "ledger", "total")
        self.assertEqual(proc.returncode, 0, proc.stdout)
        self.assertEqual(out["cases"], 0)
        self.assertEqual(out["saved_per_year"], 0)
        self.assertEqual(out["by_pack"], {})

    def test_ledger_add_unknown_case_errors(self):
        proc, _ = run_bt_json(
            self.home, "ledger", "add", "bills-20000101-0000",
            "--before", "80", "--after", "60", "--period", "month",
        )
        self.assertEqual(proc.returncode, 2)

    # Generated by /ship coverage audit.
    # Value: protects=ledger add derives the pack from the case id when
    # brief.yaml has no pack key, so totals still group by pack;
    # fails_when=the rsplit fallback in ledger.add is dropped;
    # why_new=fixture briefs always carried a pack; seam=none
    def test_pack_falls_back_to_case_id_prefix(self):
        case_id, case_dir = new_case(self.home, pack="job-offer")
        brief_path = case_dir / "brief.yaml"
        brief = yaml.load(brief_path.read_text())
        del brief["pack"]
        brief_path.write_text(yaml.dump(brief))
        proc, out = run_bt_json(
            self.home, "ledger", "add", case_id,
            "--before", "120", "--after", "100", "--period", "year",
        )
        self.assertEqual(proc.returncode, 0, proc.stdout)
        proc, out = run_bt_json(self.home, "ledger", "total")
        self.assertEqual(proc.returncode, 0, proc.stdout)
        self.assertEqual(out["by_pack"], {"job-offer": 20})

    # Generated by /ship coverage audit.
    # Value: protects=a corrupt line in ledger.jsonl makes ledger total
    # exit 2 with an error object, never a traceback or a silent wrong
    # total; fails_when=a bad JSON line or a non-object record escapes
    # the error handler; why_new=only well-formed ledger rows were
    # tested; seam=none
    def test_corrupt_ledger_line_errors(self):
        case_id, _ = new_case(self.home)
        run_bt_json(
            self.home, "ledger", "add", case_id,
            "--before", "100", "--after", "80", "--period", "month",
        )
        ledger = self.home / "ledger.jsonl"
        good = ledger.read_text()
        for corrupt in ("[1, 2]\n", "not json\n", '{"saved_per_year": "x"}\n'):
            with self.subTest(corrupt=corrupt.strip()):
                ledger.write_text(good + corrupt)
                proc, out = run_bt_json(self.home, "ledger", "total")
                self.assertEqual(proc.returncode, 2, out)
                self.assertIn("error", out)
        ledger.write_text(good)

    def test_ledger_rejects_non_finite_and_negative(self):
        case_id, _ = new_case(self.home)
        rows = [
            ("nan", "60"),
            ("inf", "60"),
            ("80", "inf"),
            ("-5", "60"),
            ("80", "-1"),
            ("-inf", "60"),
        ]
        for before, after in rows:
            with self.subTest(before=before, after=after):
                proc, out = run_bt_json(
                    self.home,
                    "ledger", "add", case_id,
                    f"--before={before}", f"--after={after}",
                    "--period", "month",
                )
                self.assertEqual(proc.returncode, 2, out)
                self.assertIn("error", out)
        self.assertFalse((self.home / "ledger.jsonl").exists())

    def test_ledger_add_invalid_direction_errors(self):
        # direction comes from cases.direction_of: an unknown value is
        # broken case data, exit 2, never a silent "pay" default.
        case_id, case_dir = new_case(self.home)
        brief_path = case_dir / "brief.yaml"
        brief = yaml.load(brief_path.read_text())
        brief["direction"] = "sideways"
        brief_path.write_text(yaml.dump(brief))
        proc, out = run_bt_json(
            self.home,
            "ledger", "add", case_id,
            "--before", "80", "--after", "60", "--period", "month",
        )
        self.assertEqual(proc.returncode, 2, out)
        self.assertIn("error", out)

    def test_ledger_rejects_duplicate_case(self):
        case_id, _ = new_case(self.home)
        args = (
            "ledger", "add", case_id,
            "--before", "80", "--after", "60", "--period", "month",
        )
        proc, _ = run_bt_json(self.home, *args)
        self.assertEqual(proc.returncode, 0)
        proc, out = run_bt_json(self.home, *args)
        self.assertEqual(proc.returncode, 2, out)
        self.assertIn("error", out)
        # Only the first entry landed.
        lines = (self.home / "ledger.jsonl").read_text().splitlines()
        self.assertEqual(len(lines), 1)


if __name__ == "__main__":
    unittest.main()
