"""Gate edge cases: verdict precedence, action validation and amounts
written with a digit plus a scale word."""

import unittest

from bt_helpers import (
    BRIEF_PAY,
    PLAN_BILLS,
    BtTestCase,
    new_case,
    plan_for,
    run_bt_json,
    write_case_files,
    write_draft,
)

LIMITS = "outside your limits; escalate to the user"


class GateEdgeTest(BtTestCase):
    def make_case(self, direction="pay", floor=1200, plan=None):
        case_id, case_dir = new_case(self.home, direction=direction)
        write_case_files(
            case_dir,
            brief=dict(BRIEF_PAY, direction=direction),
            plan=plan_for(direction, floor) if plan is None else plan,
            floor=floor,
        )
        return case_id

    def gate(self, case_id, draft, approved=False):
        args = ["gate", case_id, "--draft", str(write_draft(self.tmp, draft))]
        if approved:
            args.append("--approved")
        return run_bt_json(self.home, *args)

    # Generated by /ship coverage audit.
    # Value: protects=a block finding always wins over needs_approval, and a
    # draft with a missing or unknown action blocks (exit 1); fails_when=the
    # verdict order flips or the ACTIONS guard is dropped or loosened;
    # why_new=test_gate.py covers each rule alone, never two at once or a
    # bad action; seam=none
    def test_block_dominates_and_bad_actions_block(self):
        case_id = self.make_case(floor=1200)
        rows = [
            # (draft, approved, reason fragment)
            (
                {"action": "accept", "offer": 1300, "text": "deal"},
                False,
                LIMITS,
            ),
            (
                {"action": "accept", "offer": 1300, "text": "deal"},
                True,
                LIMITS,
            ),
            ({"offer": 1100, "text": "hello"}, False, "not one of"),
            ({"action": "Send", "offer": 1100, "text": "hello"}, False, "not one of"),
            ({"action": "wire", "offer": 1100, "text": "hello"}, True, "not one of"),
        ]
        for draft, approved, fragment in rows:
            with self.subTest(draft=draft, approved=approved):
                proc, out = self.gate(case_id, dict(draft, claims=[]), approved)
                self.assertEqual(proc.returncode, 1, out)
                self.assertEqual(out["result"], "block")
                self.assertIn(fragment, " ".join(out["reasons"]))

    # Generated by /ship coverage audit.
    # Value: protects=a draft quoting the plan target as "$1.2 million"
    # passes the untraced-number rule; fails_when=money.find reports the
    # "$1.2" prefix of "$1.2 million" as its own 1.2 amount; why_new=no test
    # writes a digit plus scale word after a currency sign; seam=none
    def test_target_written_as_dollar_millions_is_traced(self):
        plan = dict(PLAN_BILLS, target=1200000, options=[], ladder=[], facts=[])
        case_id = self.make_case(direction="receive", floor=1100000, plan=plan)
        proc, out = self.gate(
            case_id,
            {
                "action": "send",
                "offer": 1200000,
                "text": "We can close at $1.2 million.",
                "claims": [],
            },
        )
        self.assertEqual(out["reasons"], [])
        self.assertEqual(proc.returncode, 0, out)

    # Generated by /ship coverage audit.
    # Value: protects=a draft whose offer is present but not a plain
    # number blocks instead of silently skipping the floor rule, and a
    # null offer still passes; fails_when=gate.check coerces or ignores a
    # string, list, mapping or bool offer; why_new=every draft fixture
    # used a numeric offer; seam=none
    def test_offer_that_is_not_a_number_blocks(self):
        case_id = self.make_case(floor=1200)
        bad_offers = ("$1,250", "about 1200", "1200", [1200], True, {"x": 1})
        for offer in bad_offers:
            with self.subTest(offer=offer):
                proc, out = self.gate(
                    case_id,
                    {"action": "send", "offer": offer, "text": "counter", "claims": []},
                )
                self.assertEqual(proc.returncode, 1, out)
                self.assertEqual(out["result"], "block")
                self.assertIn("offer must be a number", out["reasons"])
        proc, out = self.gate(
            case_id,
            {"action": "send", "offer": None, "text": "counter", "claims": []},
        )
        self.assertEqual(proc.returncode, 0, out)
        self.assertEqual(out["reasons"], [])

    # Generated by /ship coverage audit.
    # Value: protects=bt.py exits 2 with an error object when a draft or
    # inbound file is malformed YAML or parses to a non-mapping;
    # fails_when=_load_yaml_file lets a parse error or a list through to
    # gate.check; why_new=only a missing inbound file was tested;
    # seam=none
    def test_malformed_or_non_mapping_draft_and_inbound_error(self):
        case_id = self.make_case(floor=1200)
        good = self.tmp / "good.yaml"
        good.write_text("action: send\noffer: 1100\ntext: hi\nclaims: []\n")
        bad = self.tmp / "bad.yaml"
        bad.write_text("offer: [unclosed\n")
        lst = self.tmp / "list.yaml"
        lst.write_text("- action\n- send\n")
        rows = [(bad, None), (lst, None), (good, bad), (good, lst)]
        for draft_path, inbound_path in rows:
            with self.subTest(draft=draft_path.name, inbound=inbound_path):
                args = ["gate", case_id, "--draft", str(draft_path)]
                if inbound_path is not None:
                    args += ["--inbound", str(inbound_path)]
                proc, out = run_bt_json(self.home, *args)
                self.assertEqual(proc.returncode, 2, out)
                self.assertIn("error", out)

    # Generated by /ship coverage audit.
    # Value: protects=corrupt brief.yaml, plan.yaml or a non-numeric
    # .floor make gate and score exit 2, never pass on defaults;
    # fails_when=a loader swallows a parse error and the gate or scorer
    # proceeds on empty data; why_new=missing files were tested, corrupt
    # contents were not; seam=none
    def test_corrupt_case_files_error(self):
        case_id, case_dir = new_case(self.home, direction="pay")
        write_case_files(
            case_dir, brief=dict(BRIEF_PAY), plan=PLAN_BILLS, floor=1200,
        )
        draft = write_draft(
            self.tmp,
            {"action": "send", "offer": 1100, "text": "hi", "claims": []},
        )
        inbound = self.tmp / "inbound.yaml"
        inbound.write_text("offer: 1100\ntext: counter\n")
        originals = {
            name: (case_dir / name).read_text()
            for name in ("brief.yaml", "plan.yaml", ".floor")
        }
        rows = [
            ("brief.yaml", "pack: [unclosed\n", 2),
            ("plan.yaml", "target: [unclosed\n", 2),
            ("brief.yaml", "- a\n- b\n", 2),
            # A corrupt .floor file is a runtime limit failure: the gate
            # blocks (exit 1) instead of trusting a guess, while the
            # scorer reports the error (exit 2).
            (".floor", "not a number\n", 1),
        ]
        for name, content, gate_rc in rows:
            with self.subTest(corrupt=f"{name}: {content.strip()}"):
                path = case_dir / name
                path.write_text(content)
                try:
                    proc, out = run_bt_json(
                        self.home, "gate", case_id, "--draft", str(draft)
                    )
                    self.assertEqual(proc.returncode, gate_rc, out)
                    if gate_rc == 1:
                        self.assertEqual(out["result"], "block")
                        self.assertIn(LIMITS, out["reasons"])
                    else:
                        self.assertIn("error", out)
                    proc, out = run_bt_json(
                        self.home, "score", case_id, "--inbound", str(inbound)
                    )
                    self.assertEqual(proc.returncode, 2, out)
                    self.assertIn("error", out)
                finally:
                    path.write_text(originals[name])

    # Generated by /ship coverage audit.
    # Value: protects=a draft quoting the plan's target, an option value
    # or a ladder value passes the untraced-number rule; fails_when=the
    # allowed list in gate.check drops one of the plan value sources;
    # why_new=only the offer and fact amounts were tested as traced;
    # seam=none
    def test_plan_target_options_and_ladder_values_trace(self):
        case_id = self.make_case(floor=1200)
        proc, out = self.gate(
            case_id,
            {
                "action": "send",
                "offer": 1100,
                "text": "I can do $1,100 monthly, $950 annually, or $1,000 "
                "with a longer term, up to $1,150 pushed",
                "claims": [],
            },
        )
        self.assertEqual(out["reasons"], [])
        self.assertEqual(proc.returncode, 0, out)

    # Generated by /ship coverage audit.
    # Value: protects=the same untraced amount repeated in a draft raises
    # one block reason, not one per occurrence; fails_when=the seen set
    # in the untraced loop is dropped; why_new=untraced amounts were only
    # tested once each; seam=none
    def test_repeated_untraced_amount_reported_once(self):
        case_id = self.make_case(floor=1200, plan={**PLAN_BILLS, "facts": []})
        proc, out = self.gate(
            case_id,
            {
                "action": "send",
                "offer": 1100,
                "text": "not $55, I said not $55",
                "claims": [],
            },
        )
        self.assertEqual(proc.returncode, 1, out)
        untraced = [r for r in out["reasons"] if "untraced number" in r]
        self.assertEqual(len(untraced), 1, out)


if __name__ == "__main__":
    unittest.main()
