import unittest
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "skills" / "betterterms-guardrails" / "scripts"))

from btlib import money


class AmountsTest(unittest.TestCase):
    def test_dollar_commas(self):
        self.assertEqual(money.amounts("$1,200"), [1200.0])

    def test_decimal(self):
        self.assertEqual(money.amounts("1200.00"), [1200.0])

    def test_k_suffix(self):
        self.assertEqual(money.amounts("1.2k"), [1200.0])

    def test_currency_code(self):
        self.assertEqual(money.amounts("USD 1200"), [1200.0])

    def test_currency_symbol_code(self):
        self.assertEqual(money.amounts("S$1,200"), [1200.0])

    def test_spelled_hundreds(self):
        self.assertEqual(money.amounts("twelve hundred"), [1200.0])

    def test_spelled_thousands(self):
        self.assertIn(1200.0, money.amounts("one thousand two hundred"))

    def test_spelled_millions(self):
        self.assertIn(2000000.0, money.amounts("two million"))

    def test_spelled_with_currency_word(self):
        self.assertIn(350000.0, money.amounts("three hundred fifty thousand dollars"))

    def test_dollars_suffix(self):
        self.assertEqual(money.amounts("1200 dollars"), [1200.0])

    def test_fact_id_is_not_an_amount(self):
        self.assertEqual(money.amounts("claim f9 is wrong"), [])

    def test_no_amounts(self):
        self.assertEqual(money.amounts("see you next week"), [])

    def test_currency_marked_flag(self):
        marked = {a.value for a in money.find("pay $1,200 over 3 years") if a.marked}
        self.assertEqual(marked, {1200.0})

    def test_bare_number_unmarked(self):
        found = money.find("I have 3 options")
        self.assertTrue(any(a.value == 3.0 and not a.marked for a in found))

    # Generated by /ship coverage audit.
    # Value: protects=compact scale suffixes parse to full amounts: 5m and
    # 5mm are 5,000,000, 2bn is 2,000,000,000; fails_when=a suffix is
    # dropped from the multiplier table or "mm" is left unread;
    # why_new=only the k suffix was tested; seam=none
    def test_compact_scale_suffixes(self):
        self.assertEqual(money.amounts("5m"), [5000000.0])
        self.assertEqual(money.amounts("5mm"), [5000000.0])
        self.assertEqual(money.amounts("2bn"), [2000000000.0])

    # Generated by /ship coverage audit.
    # Value: protects=a bare number followed by an ISO currency code is a
    # marked amount; fails_when=the code-suffix alternative in _SUFFIXED
    # is dropped; why_new=only currency prefixes and word suffixes were
    # tested; seam=none
    def test_currency_code_suffix_is_marked(self):
        found = money.find("send 1200 EUR today")
        self.assertEqual([(a.value, a.marked) for a in found], [(1200.0, True)])

    # Generated by /ship coverage audit.
    # Value: protects="$1.2 million" reads as one marked 1,200,000 amount,
    # never a spurious 1.2 plus a separate million; fails_when=_MARKED
    # stops at the number and _DIGIT_SCALE emits a second overlapping
    # amount; why_new=no test put a scale word after a currency-marked
    # number; seam=none
    def test_dollar_millions_is_one_marked_amount(self):
        found = money.find("we close at $1.2 million")
        self.assertEqual([(a.value, a.marked) for a in found], [(1200000.0, True)])

    # Generated by /ship coverage audit.
    # Value: protects=digits plus a scale word collapse to one amount:
    # "1.5 thousand" is 1500 and "12 hundred" is 1200; fails_when=
    # _DIGIT_SCALE loses "hundred" or reports digit and scale separately;
    # why_new=scale words were only exercised spelled out; seam=none
    def test_digit_scale_words(self):
        self.assertEqual(money.amounts("1.5 thousand"), [1500.0])
        self.assertEqual(money.amounts("12 hundred"), [1200.0])


if __name__ == "__main__":
    unittest.main()
