"""Placeholder index bounds (adversarial review fix): an index longer
than four ASCII digits is a malformed placeholder and never reaches
``int``; the block reason stays bounded no matter how long the digit
run is.
"""

import unittest

from bt_helpers import (
    BRIEF_PAY,
    PLAN_BILLS,
    BtTestCase,
    new_case,
    run_bt_json,
    send_draft,
    write_case_files,
    write_draft,
)


class IndexBoundsTest(BtTestCase):
    def make_case(self):
        case_id, case_dir = new_case(self.home)
        write_case_files(
            case_dir,
            brief=dict(BRIEF_PAY),
            plan=dict(PLAN_BILLS),
            floor=1200,
        )
        return case_id

    def gate(self, case_id, template):
        path = write_draft(self.tmp, send_draft(template=template))
        return run_bt_json(
            self.home, "gate", case_id, "--draft", str(path)
        )

    def test_oversized_ladder_index_blocks_malformed(self):
        # Five or more digits never reach int(): a huge run is a
        # malformed placeholder, blocked without converting it.
        case_id = self.make_case()
        for arg in ("12345", "9" * 5000):
            with self.subTest(arg=arg[:12]):
                proc, out = self.gate(
                    case_id, f"price {{ladder:{arg}}}"
                )
                self.assertEqual(proc.returncode, 1, out)
                self.assertIn(
                    "malformed placeholder", " ".join(out["reasons"])
                )
        # The reason stays bounded: the digit run is not quoted whole.
        proc, out = self.gate(case_id, "price {ladder:" + "9" * 5000 + "}")
        self.assertLess(max(len(r) for r in out["reasons"]), 200)

    def test_oversized_quote_index_blocks_malformed(self):
        case_id = self.make_case()
        proc, out = self.gate(case_id, "you said {quote:99999}")
        self.assertEqual(proc.returncode, 1, out)
        self.assertIn(
            "malformed placeholder", " ".join(out["reasons"])
        )

    def test_four_digit_index_still_parses(self):
        # The bound is five digits: a four-digit index is a valid (if
        # out of range) index, blocked as before.
        case_id = self.make_case()
        proc, out = self.gate(case_id, "price {ladder:9999}")
        self.assertEqual(proc.returncode, 1, out)
        self.assertIn("needs an index", " ".join(out["reasons"]))

    # Generated by /ship coverage audit.
    # Value: protects={ladder:n} and {option:L} on a plan entry with no
    #   usable number block naming the placeholder (exit 1);
    #   fails_when=the "has no value" guards in render are dropped and
    #   money_text(None) crashes to exit 2 or renders a bogus amount;
    #   why_new=no test reaches render.py's option/ladder no-value
    #   branches or a bare-scalar ladder entry; seam=none
    def test_plan_entry_without_a_number_blocks_naming_it(self):
        case_id, case_dir = new_case(self.home)
        plan = dict(
            PLAN_BILLS,
            options=[{"label": "x", "value": None},
                     {"label": "y", "value": "soon"}],
            ladder=[1100, {"value": None}, {"value": "soon"}],
        )
        write_case_files(
            case_dir, brief=dict(BRIEF_PAY), plan=plan, floor=1200
        )
        for tag in ("{ladder:1}", "{ladder:2}", "{ladder:3}",
                    "{option:x}", "{option:y}"):
            with self.subTest(tag=tag):
                proc, out = self.gate(case_id, f"our price is {tag}")
                self.assertEqual(proc.returncode, 1, out)
                self.assertIsNone(out["rendered"])
                self.assertIn(f"{tag} has no value", out["reasons"])


if __name__ == "__main__":
    unittest.main()
