"""Verify checks that shell out to repo scripts or host validators, plus the
file-size rule for extensionless scripts/ entry points."""

import contextlib
import io
import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from test_scripts import make_repo
from test_verify import VERIFY_MOD, assert_failed, make_repo_root, run_verify


class VerifyToolChecksTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)

    # Generated by /ship coverage audit.
    # Value: protects=verify FAILs build-fresh, version-sync and claude-validate
    # when the script or host validator exits non-zero, and PASSes on exit 0;
    # fails_when=_run_script or _validate ignores the return code; why_new=
    # verify tests only reach the SKIP branches of these checks; seam=none
    @unittest.skipIf(os.name == "nt", "fake validators are POSIX shell scripts")
    def test_failing_script_or_validator_fails_named_check(self):
        root = make_repo(Path(self.tmp.name) / "repo")
        # build --check fails on a stale generated file; bump-version
        # --check on bad semver.
        build = root / "scripts" / "build"
        build.write_text(
            build.read_text().replace(
                "GENERATORS = []",
                "GENERATORS = "
                "[lambda root, version: {'stale.txt': 'expected\\n'}]",
                1,
            )
        )
        (root / "stale.txt").write_text("drifted\n")
        (root / "VERSION").write_text("not-semver\n")
        (root / ".claude-plugin").mkdir()
        (root / ".claude-plugin" / "plugin.json").write_text('{"name": "x"}\n')
        (root / "gemini-extension.json").write_text('{"name": "x"}\n')
        fakebin = Path(self.tmp.name) / "bin"
        fakebin.mkdir()
        for tool, rc in (("claude", 1), ("gemini", 0)):
            exe = fakebin / tool
            exe.write_text(
                f"#!/bin/sh\necho '{tool} says manifest invalid' >&2\nexit {rc}\n"
            )
            exe.chmod(0o755)
        path = str(fakebin) + os.pathsep + os.environ.get("PATH", "")
        with mock.patch.dict(os.environ, {"PATH": path}):
            proc = run_verify(root)
        assert_failed(self, proc, "build-fresh")
        self.assertIn("stale.txt", proc.stdout)
        assert_failed(self, proc, "version-sync")
        self.assertIn("not X.Y.Z semver", proc.stdout)
        assert_failed(self, proc, "claude-validate")
        self.assertIn("claude says manifest invalid", proc.stdout)
        self.assertIn("PASS gemini-validate", proc.stdout)

    # Generated by /ship coverage audit.
    # Value: protects=a host validator whose manifest exists but whose CLI is
    # not on PATH SKIPs instead of FAILing or crashing; fails_when=the
    # shutil.which guard in _validate is removed or inverted; why_new=tests
    # cover no-marker SKIP and installed-CLI PASS/FAIL only; seam=none
    def test_validator_skips_when_cli_missing(self):
        root = Path(self.tmp.name)
        make_repo_root(root)
        (root / ".claude-plugin").mkdir()
        (root / ".claude-plugin" / "plugin.json").write_text('{"name": "x"}\n')
        (root / "gemini-extension.json").write_text('{"name": "x"}\n')
        empty = root / "emptybin"
        empty.mkdir()
        with mock.patch.dict(os.environ, {"PATH": str(empty)}):
            proc = run_verify(root)
        self.assertIn("SKIP claude-validate: claude not installed", proc.stdout)
        self.assertIn("SKIP gemini-validate: gemini not installed", proc.stdout)
        self.assertNotIn("FAIL", proc.stdout)

    # Generated by /ship coverage audit.
    # Value: protects=a check that raises prints 'FAIL <name>: internal error'
    # and later checks still run; fails_when=main() drops the try/except
    # around each check or stops the loop on the first exception; why_new=no
    # test makes a check raise; seam=none
    def test_raising_check_fails_and_later_checks_run(self):
        root = Path(self.tmp.name)
        make_repo_root(root)

        def boom(_root):
            raise RuntimeError("kaboom")

        checks = [("boom", boom), ("after", lambda _root: ("PASS", ""))]
        with mock.patch.object(VERIFY_MOD, "CHECKS", checks):
            proc = run_verify(root)
        self.assertEqual(proc.returncode, 1, proc.stdout + proc.stderr)
        self.assertIn("FAIL boom: internal error: kaboom", proc.stdout)
        self.assertIn("PASS after", proc.stdout)

    # Generated by /ship coverage audit.
    # Value: protects=the 400-line cap applies to extensionless scripts/ entry
    # points (scripts/verify is near it) but not to other extensionless files;
    # fails_when=the scripts_file clause in check_file_size is dropped or
    # widened; why_new=size tests only use a .py file; seam=none
    def test_file_size_counts_extensionless_scripts_only(self):
        root = Path(self.tmp.name)
        make_repo_root(root)
        (root / "scripts").mkdir()
        (root / "scripts" / "tool").write_text("x = 1\n" * 401)
        (root / "scripts" / "data.txt").write_text("row\n" * 401)
        (root / "Makefile").write_text("x:\n" * 401)
        proc = run_verify(root)
        assert_failed(self, proc, "file-size")
        self.assertIn("scripts/tool (401 lines > 400)", proc.stdout)
        self.assertNotIn("data.txt", proc.stdout)
        self.assertNotIn("Makefile", proc.stdout)
        (root / "scripts" / "tool").write_text("x = 1\n" * 400)
        self.assertIn("PASS file-size", run_verify(root).stdout)

    # Generated by /ship coverage audit.
    # Value: protects=verify 'all' means this repo's root and two or more args
    # exit 2 with usage before any check runs; fails_when=the 'all' alias or
    # the argv-count guard in main() is dropped; why_new=bad-root tests pass
    # one real path only; seam=none
    def test_all_alias_and_extra_args(self):
        ran = []
        checks = [("probe", lambda root: ran.append(root) or ("PASS", ""))]
        with mock.patch.object(VERIFY_MOD, "CHECKS", checks):
            proc = run_verify("all")
            self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
            self.assertEqual(ran, [VERIFY_MOD.REPO_ROOT])
            out, err = io.StringIO(), io.StringIO()
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                code = VERIFY_MOD.main([self.tmp.name, "extra"])
        self.assertEqual(code, 2)
        self.assertIn("Usage", err.getvalue())
        self.assertEqual(ran, [VERIFY_MOD.REPO_ROOT])

    def test_file_size_counts_ts_and_sh_sources(self):
        root = Path(self.tmp.name)
        make_repo_root(root)
        (root / "big.ts").write_text("x = 1\n" * 401)
        (root / "big.sh").write_text("echo x\n" * 401)
        (root / "big.txt").write_text("row\n" * 401)
        proc = run_verify(root)
        assert_failed(self, proc, "file-size")
        self.assertIn("big.ts (401 lines > 400)", proc.stdout)
        self.assertIn("big.sh (401 lines > 400)", proc.stdout)
        self.assertNotIn("big.txt", proc.stdout)


if __name__ == "__main__":
    unittest.main()
