import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts._lib import frontmatter

SKILL = """\
---
name: betterterms-x
description: Does a thing. Use when the user asks for the thing.
---
Body starts here.
Second line.
"""


class ParseTest(unittest.TestCase):
    def _write(self, text):
        tmp = tempfile.NamedTemporaryFile("w", suffix=".md", delete=False)
        tmp.write(text)
        tmp.close()
        self.addCleanup(Path(tmp.name).unlink)
        return Path(tmp.name)

    def test_parses_name_description_and_body(self):
        fm, body = frontmatter.parse(self._write(SKILL))
        self.assertEqual(fm["name"], "betterterms-x")
        self.assertEqual(
            fm["description"], "Does a thing. Use when the user asks for the thing."
        )
        self.assertEqual(body, "Body starts here.\nSecond line.\n")

    def test_missing_closing_marker_raises(self):
        path = self._write("---\nname: x\ndescription: never closed\n")
        with self.assertRaises(frontmatter.Error):
            frontmatter.parse(path)

    def test_no_frontmatter_returns_empty_dict(self):
        fm, body = frontmatter.parse(self._write("plain markdown\n"))
        self.assertEqual(fm, {})
        self.assertEqual(body, "plain markdown\n")

    # Generated by /ship coverage audit.
    # Value: protects=an empty '---' block parses as {} and a non-mapping block
    # raises frontmatter.Error; fails_when=the None->{} fallback or the mapping
    # guard in parse() is removed; why_new=tests cover only valid, unclosed and
    # absent frontmatter; seam=none
    def test_empty_block_is_empty_dict_and_list_block_raises(self):
        fm, body = frontmatter.parse(self._write("---\n---\nbody\n"))
        self.assertEqual(fm, {})
        self.assertEqual(body, "body\n")
        with self.assertRaises(frontmatter.Error) as cm:
            frontmatter.parse(self._write("---\n- a\n- b\n---\nbody\n"))
        self.assertIn("not a mapping", str(cm.exception))

    def test_indented_closing_marker_does_not_close(self):
        with self.assertRaises(frontmatter.Error):
            frontmatter.parse(self._write("---\nname: x\n  ---\nbody\n"))

    def test_leading_bom_is_stripped(self):
        fm, body = frontmatter.parse(self._write("\ufeff---\nname: x\n---\nbody\n"))
        self.assertEqual(fm["name"], "x")
        self.assertEqual(body, "body\n")

    def test_plain_value_with_colon_space_rejected(self):
        with self.assertRaises(frontmatter.Error):
            frontmatter.parse(self._write("---\ndescription: a: b\n---\nbody\n"))

    def test_error_names_file_line_not_block_line(self):
        path = self._write("---\nname: x\ndescription: a: b\n---\nbody\n")
        with self.assertRaises(frontmatter.Error) as cm:
            frontmatter.parse(path)
        self.assertIn("line 3", str(cm.exception))

    def test_indicator_start_value_rejected_but_flow_ok(self):
        for v in ("- x", "? x", ": x", ",x", "*a", "&a", "!t", ">x", "%p", "@r", "`z`"):
            with self.subTest(v=v):
                with self.assertRaises(frontmatter.Error):
                    frontmatter.parse(self._write(f"---\ndescription: {v}\n---\nbody\n"))
        fm, _ = frontmatter.parse(
            self._write('---\ndescription: "a: b"\nallowed-tools: [Read, Bash]\n---\nbody\n')
        )
        self.assertEqual(fm["allowed-tools"], ["Read", "Bash"])
        fm, _ = frontmatter.parse(
            self._write("---\ndescription: |\n  a: b\n  note: x: y\n---\nbody\n")
        )
        self.assertEqual(fm["description"], "a: b\nnote: x: y\n")


if __name__ == "__main__":
    unittest.main()
